export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";

export const GET_SINGLE_PRODUCT_FOR_USER_REQUEST =
  "GET_SINGLE_PRODUCT_FOR_USER_REQUEST";
export const GET_SINGLE_PRODUCT_FOR_USER_SUCCESS =
  "GET_SINGLE_PRODUCT_FOR_USER_SUCCESS";
export const GET_SINGLE_PRODUCT_FOR_USER_FAIL =
  "GET_SINGLE_PRODUCT_FOR_USER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
