export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAILURE";

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const EDIT_USERNAME_REQUEST = "EDIT_USERNAME_REQUEST";
export const EDIT_USERNAME_SUCCESS = "EDIT_USERNAME_SUCCESS";
export const EDIT_USERNAME_RESET = "EDIT_USERnAMES_RESET";
export const EDIT_USERNAME_FAIL = "EDIT_USERNAME_FAIL";

export const USER_SIGNOUT_REQUEST = "USER_SIGNOUT_REQUEST";
export const USER_SIGNOUT_SUCCESS = "USER_SIGNOUT_SUCCESS";
export const USER_SIGNOUT_FAIL = "USER_SIGNOUT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
